import logging

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.api import activity, agent, auth, chat, documents, email, projects, vision
from app.core.config import FRONTEND_URL

logger = logging.getLogger(__name__)

app = FastAPI(title="AI Engineering Assistant")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[FRONTEND_URL],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    # An uncaught exception's default error response bypasses CORSMiddleware
    # (it's generated by the outer ServerErrorMiddleware, not routed back
    # through the CORS-header-adding layer), so the browser can't read it
    # and reports a generic "Failed to fetch" with the real error hidden.
    # Handling it here keeps the response inside the CORS-aware path.
    logger.exception("Unhandled exception on %s %s", request.method, request.url.path)
    return JSONResponse(status_code=500, content={"detail": "Internal server error"})


app.include_router(auth.router)
app.include_router(projects.router)
app.include_router(documents.router)
app.include_router(chat.router)
app.include_router(chat.conversation_router)
app.include_router(vision.router)
app.include_router(agent.router)
app.include_router(email.router)
app.include_router(activity.router)


@app.get("/api/health")
def health() -> dict:
    return {"status": "ok", "services": {"api": "ok"}}
